import React, { useContext, useEffect, useState } from "react";

import { useParams } from "react-router-dom";
import MyContext from "../ContextApi/MyContext";
import Loader from "./Loader/Loader";
import axios from "axios";
import { toast } from "react-toastify";
import { getMediaById } from "./Admin/Media/mediaApi";



const MediaCard  = () => {
  const { Id } = useParams();

  const [loading, setLoading] = useState(true);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [image, setImage] = useState("");
  const [date, setDate] = useState("");
  const { api, imgapi, preview } = useContext(MyContext);
  const [category1, setCategory1] = useState("");



  useEffect(() => {
    const loadBlog = async () => {
      try {
        const data = await getMediaById(api, Id);
        // console.log("blog edit", data);
        setTitle(data.title || "");
        setDescription(data.description || "");
        setImage(data.photo_upload || null); // store image path
        console.log(data);
        setCategory1(data.category || "")

        const formattedDate = new Date(data.created_at).toLocaleDateString(
          "en-US",
          {
            year: "numeric",
            month: "short",
            day: "2-digit",
          }
        );
        setDate(formattedDate);
      } catch (error) {
        toast.error("Failed to fetch blog data");
      } finally {
        setLoading(false);
      }
    };

    loadBlog();
  }, [api, Id]);

  if (loading) return <Loader />;
  return (
    <div className="mt-20">
      <div
        className="relative w-full h-[200px] bg-cover bg-center"
        style={{
          backgroundImage: `url(${preview})`,
        }}
      >
        <div
          className="absolute inset-0 z-10"
          style={{ backgroundColor: "rgba(73, 71, 71, 0.6)" }}
        />
        <div className="absolute inset-0 z-20 flex items-center justify-center md:justify-start md:px-40">
          <p className="text-2xl md:text-4xl font-semibold text-white">{category1}</p>
        </div>
      </div>
      {/* <p className=" px-35 mt-5">
        <span>Blog</span> <span>{title}</span>
      </p> */}
      <div className="max-w-7xl mx-auto flex flex-col lg:flex-row gap-10 px-4 py-10">
        {/* Blog Detail */}

        <div className="lg:w-2/3 w-full">
          <img
            src={`${imgapi}${image}`}
            alt={title}
            className="w-full h-auto rounded-md mb-2"
          />
          <p className="text-xs italic text-gray-500 mb-4">
            Image generated by AI.
          </p>
          <p className="text-gray-700 font-medium text-sm mb-2">
            Posted On: {date}
          </p>
          <h1 className="text-xl font-bold text-red-600 mb-4">{title}</h1>
          <div
            className="blog-description text-base leading-relaxed"
            dangerouslySetInnerHTML={{ __html: description }}
          />
        </div>

      </div>
    </div>
  );
};

export default MediaCard;
